/*

 SRC/MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : Map_Tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MapWidth 32
#define MapHeight 32
#define MapBank 0

#define Map MapPLN0
extern unsigned char MapPLN0[];
extern unsigned char MapPLN1[];

/* End of SRC/MAP.H */
