/*

 SRC/MAPTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 31

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define MapTilesBank 0

/* Super Gameboy palette 0 */
#define MapTilesSGBPal0c0 6076
#define MapTilesSGBPal0c1 8935
#define MapTilesSGBPal0c2 6596
#define MapTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define MapTilesSGBPal1c0 6076
#define MapTilesSGBPal1c1 8935
#define MapTilesSGBPal1c2 6596
#define MapTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define MapTilesSGBPal2c0 6076
#define MapTilesSGBPal2c1 8935
#define MapTilesSGBPal2c2 6596
#define MapTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define MapTilesSGBPal3c0 6076
#define MapTilesSGBPal3c1 8935
#define MapTilesSGBPal3c2 6596
#define MapTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define MapTilesCGBPal0c0 819
#define MapTilesCGBPal0c1 1484
#define MapTilesCGBPal0c2 1255
#define MapTilesCGBPal0c3 27200

/* Gameboy Color palette 1 */
#define MapTilesCGBPal1c0 21246
#define MapTilesCGBPal1c1 2335
#define MapTilesCGBPal1c2 145
#define MapTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define MapTilesCGBPal2c0 25560
#define MapTilesCGBPal2c1 6016
#define MapTilesCGBPal2c2 4545
#define MapTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define MapTilesCGBPal3c0 31640
#define MapTilesCGBPal3c1 30336
#define MapTilesCGBPal3c2 13633
#define MapTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define MapTilesCGBPal4c0 23516
#define MapTilesCGBPal4c1 921
#define MapTilesCGBPal4c2 1484
#define MapTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define MapTilesCGBPal5c0 31582
#define MapTilesCGBPal5c1 32063
#define MapTilesCGBPal5c2 20503
#define MapTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define MapTilesCGBPal6c0 24446
#define MapTilesCGBPal6c1 666
#define MapTilesCGBPal6c2 1390
#define MapTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define MapTilesCGBPal7c0 31479
#define MapTilesCGBPal7c1 32105
#define MapTilesCGBPal7c2 14369
#define MapTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char MapTilesCGB[];
/* Start of tile array. */
extern unsigned char MapTiles[];

/* End of SRC/MAPTILES.H */
