/*

 SRC/PARALLAXTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 511

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define ParallaxTilesBank 0

/* Super Gameboy palette 0 */
#define ParallaxTilesSGBPal0c0 6076
#define ParallaxTilesSGBPal0c1 8935
#define ParallaxTilesSGBPal0c2 6596
#define ParallaxTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define ParallaxTilesSGBPal1c0 6076
#define ParallaxTilesSGBPal1c1 8935
#define ParallaxTilesSGBPal1c2 6596
#define ParallaxTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define ParallaxTilesSGBPal2c0 6076
#define ParallaxTilesSGBPal2c1 8935
#define ParallaxTilesSGBPal2c2 6596
#define ParallaxTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define ParallaxTilesSGBPal3c0 6076
#define ParallaxTilesSGBPal3c1 8935
#define ParallaxTilesSGBPal3c2 6596
#define ParallaxTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define ParallaxTilesCGBPal0c0 21467
#define ParallaxTilesCGBPal0c1 816
#define ParallaxTilesCGBPal0c2 1480
#define ParallaxTilesCGBPal0c3 98

/* Gameboy Color palette 1 */
#define ParallaxTilesCGBPal1c0 32767
#define ParallaxTilesCGBPal1c1 8479
#define ParallaxTilesCGBPal1c2 17
#define ParallaxTilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define ParallaxTilesCGBPal2c0 19458
#define ParallaxTilesCGBPal2c1 32767
#define ParallaxTilesCGBPal2c2 13741
#define ParallaxTilesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define ParallaxTilesCGBPal3c0 19458
#define ParallaxTilesCGBPal3c1 14317
#define ParallaxTilesCGBPal3c2 3616
#define ParallaxTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define ParallaxTilesCGBPal4c0 19458
#define ParallaxTilesCGBPal4c1 31411
#define ParallaxTilesCGBPal4c2 32102
#define ParallaxTilesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define ParallaxTilesCGBPal5c0 19458
#define ParallaxTilesCGBPal5c1 29214
#define ParallaxTilesCGBPal5c2 3616
#define ParallaxTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define ParallaxTilesCGBPal6c0 19458
#define ParallaxTilesCGBPal6c1 23254
#define ParallaxTilesCGBPal6c2 31
#define ParallaxTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define ParallaxTilesCGBPal7c0 19458
#define ParallaxTilesCGBPal7c1 9887
#define ParallaxTilesCGBPal7c2 375
#define ParallaxTilesCGBPal7c3 0
/* CGBpalette entries. */
extern unsigned char ParallaxTilesCGB[];
/* Start of tile array. */
extern unsigned char ParallaxTiles[];

/* End of SRC/PARALLAXTILES.H */
